-- ============================================================
-- GreenStep Challenge Admin -- Baseline Schema
-- ============================================================
-- Consolidated from the original migrations 001-014. The deployed
-- database already matches this state; this file exists as the
-- single readable description of "what's in the DB" plus a way to
-- recreate it from scratch via `supabase db reset`.
--
-- Sections:
--   1. Tables
--   2. Indexes
--   3. RPCs (login pre-flight + RLS helpers)
--   4. Row-Level Security (RLS) + policies
--   5. Permissions
-- ============================================================


-- ============================================================
-- 1. Tables
-- ============================================================

-- Departments / Participant Groups
create table if not exists departments (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  "createdAt" date not null default current_date
);

-- Users (app-level; mirrors the email of a Supabase auth.users row)
create table if not exists users (
  id           bigint generated by default as identity primary key,
  name         text not null,
  email        text not null unique,
  role         text not null default 'GeneralUser'
                 check (role in ('SuperAdmin', 'Admin', 'GeneralUser')),
  status       text not null default 'Active'
                 check (status in ('Active', 'Deactivated')),
  "groupId"    bigint references departments(id) on delete set null,
  department   text,
  "createdAt"  date not null default current_date,
  "lastActive" date
);

-- Dynamic action categories (Water, Food, Energy, etc.)
create table if not exists categories (
  id           serial primary key,
  name         varchar(255) not null unique,
  description  text,
  "createdAt"  timestamptz default now(),
  "updated_at" timestamptz default now()
);

-- Actions (catalog; not bound to any challenge until linked)
create table if not exists actions (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  category    text not null,
  points      integer not null default 0
);

-- Challenges
--
-- Color story: `theme` is the legacy single-color field, still read
-- by the dashboard "color dot" widgets. The four bgColor*/txColor*
-- columns power the create/edit form's full palette picker. Both
-- coexist; new rows populate the four, old rows have `theme`.
create table if not exists challenges (
  id                 bigint generated by default as identity primary key,
  name               text not null,
  description        text,
  category           text,
  theme              text default '#4CAF50',
  "bgColorHeader"    varchar(7),
  "txColorHeader"    varchar(7),
  "bgColorBody"      varchar(7),
  "txColorBody"      varchar(7),
  "startDate"        date,
  "endDate"          date,
  "joinBy"           date,
  status             text not null default 'Upcoming'
                       check (status in ('Active', 'Upcoming', 'Completed', 'Archived')),
  "createdBy"        bigint references users(id) on delete set null,
  "participantCount" integer not null default 0,
  "groupId"          bigint references departments(id) on delete set null
);

-- Challenge <-> Actions (many-to-many)
create table if not exists challenge_actions (
  "challengeId" bigint not null references challenges(id) on delete cascade,
  "actionId"    bigint not null references actions(id) on delete cascade,
  primary key ("challengeId", "actionId")
);

-- Challenge <-> Participants (many-to-many)
create table if not exists challenge_participants (
  "challengeId" bigint not null references challenges(id) on delete cascade,
  "userId"      bigint not null references users(id) on delete cascade,
  primary key ("challengeId", "userId")
);

-- Templates (the table the "Templates" UI reads/writes)
create table if not exists templates (
  id                 bigint generated by default as identity primary key,
  name               text not null,
  description        text,
  type               text,
  category           text,
  theme              text default '#4CAF50',
  "createdBy"        bigint references users(id) on delete set null,
  "createdAt"        date not null default current_date,
  "joinBy"           date,
  "participantGroup" bigint references departments(id) on delete set null
);

-- Note: the live database used to have `presets` and `preset_actions`
-- tables from before the templates rename. They have since been dropped
-- (no application code reads from them; only the legacy `deleteTemplate`
-- in `data/api/templates.js` still references `presets`, which is a known
-- bug tracked in the issue tracker). They are intentionally not recreated
-- here so a fresh DB matches the live state.

-- Participation (user action completions)
create table if not exists participation (
  id            bigint generated by default as identity primary key,
  "userId"      bigint not null references users(id) on delete cascade,
  "challengeId" bigint not null references challenges(id) on delete cascade,
  "actionId"    bigint not null references actions(id) on delete cascade,
  "completedAt" date not null,
  notes         text,
  "photoUrl"    text
);

-- Activity Logs (admin audit trail; effectively immutable -- see RLS below)
create table if not exists activity_logs (
  id        bigint generated by default as identity primary key,
  "userId"  bigint references users(id) on delete set null,
  action    text not null,
  timestamp timestamptz not null default now(),
  details   text
);


-- ============================================================
-- 2. Indexes
-- ============================================================
-- Foreign-key indexes
create index if not exists idx_users_group on users("groupId");
create index if not exists idx_users_email on users(email);
create index if not exists idx_challenges_status on challenges(status);
create index if not exists idx_challenges_group on challenges("groupId");
create index if not exists idx_participation_user on participation("userId");
create index if not exists idx_participation_challenge on participation("challengeId");
create index if not exists idx_participation_action on participation("actionId");
create index if not exists idx_activity_logs_user on activity_logs("userId");

-- Performance indexes for report/dashboard query patterns
create index if not exists idx_activity_logs_timestamp        on activity_logs(timestamp desc);
create index if not exists idx_activity_logs_user_timestamp   on activity_logs("userId", timestamp desc);
create index if not exists idx_participation_user_challenge   on participation("userId", "challengeId");
create index if not exists idx_participation_completed_at     on participation("completedAt");


-- ============================================================
-- 3. RPCs
-- ============================================================

-- Anon-callable check used by the login page to decide whether to
-- send an OTP code. `security definer` lets the inner SELECT bypass
-- RLS; only a boolean is returned. Filters out deactivated users so
-- the pre-flight rejects them before sending a code.
create or replace function public.auth_email_is_registered(email_to_check text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.users
    where email = email_to_check
      and status = 'Active'
  );
$$;
grant execute on function public.auth_email_is_registered(text) to anon, authenticated;

-- Look up the role of the currently-authenticated caller.
-- `security definer` + explicit search_path so the inner SELECT
-- bypasses RLS on public.users (otherwise the admin_write policy
-- would recursively call this function while evaluating itself).
create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.users where email = auth.email() limit 1;
$$;
grant execute on function public.current_user_role() to authenticated;

-- Convenience predicate for "may mutate admin data".
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('Admin', 'SuperAdmin'), false);
$$;
grant execute on function public.is_admin() to authenticated;


-- ============================================================
-- 4. Row-Level Security + policies
-- ============================================================
-- Threat model:
--   * anon (signed-out) -- no table access; only the
--     auth_email_is_registered RPC.
--   * authenticated     -- can SELECT every admin table.
--   * Admin / SuperAdmin -- INSERT/UPDATE/DELETE on every admin table.
--   * Any authenticated user may INSERT into participation and
--     activity_logs (mobile users log their own actions; audit log
--     writes ride along with admin operations).
--   * activity_logs has no UPDATE/DELETE policy, so RLS denies them
--     -- audit trail is effectively immutable for normal users.
--   * service_role bypasses RLS by default (used by the Vercel
--     invite-user function).

alter table public.users                  enable row level security;
alter table public.departments            enable row level security;
alter table public.actions                enable row level security;
alter table public.challenges             enable row level security;
alter table public.challenge_actions      enable row level security;
alter table public.challenge_participants enable row level security;
alter table public.templates              enable row level security;
alter table public.participation          enable row level security;
alter table public.activity_logs          enable row level security;
alter table public.categories             enable row level security;

-- Read: any authenticated user
create policy authenticated_read on public.users                  for select to authenticated using (true);
create policy authenticated_read on public.departments            for select to authenticated using (true);
create policy authenticated_read on public.actions                for select to authenticated using (true);
create policy authenticated_read on public.challenges             for select to authenticated using (true);
create policy authenticated_read on public.challenge_actions      for select to authenticated using (true);
create policy authenticated_read on public.challenge_participants for select to authenticated using (true);
create policy authenticated_read on public.templates              for select to authenticated using (true);
create policy authenticated_read on public.participation          for select to authenticated using (true);
create policy authenticated_read on public.activity_logs          for select to authenticated using (true);

-- Write: Admin / SuperAdmin only (FOR ALL covers INSERT, UPDATE, DELETE)
create policy admin_write on public.users                  for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_write on public.departments            for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_write on public.actions                for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_write on public.challenges             for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_write on public.challenge_actions      for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_write on public.challenge_participants for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_write on public.templates              for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Special cases on participation + activity_logs
create policy any_insert    on public.participation for insert to authenticated with check (true);
create policy admin_update  on public.participation for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_delete  on public.participation for delete to authenticated using (public.is_admin());
create policy any_insert    on public.activity_logs for insert to authenticated with check (true);

-- categories has its own simpler policy set (added separately)
create policy "Enable read access for all users"      on public.categories for select using (true);
create policy "Enable insert for authenticated users" on public.categories for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users" on public.categories for update using (auth.role() = 'authenticated');


-- ============================================================
-- 5. Permissions
-- ============================================================
-- Postgres checks GRANTs before RLS, so policies only matter if the
-- role also has the underlying privilege.
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
